### ISSUE TITLE
What is voidspace ?

### ISSUE THREAD

**Issue by Coretool** [lite20/Yunitto#1]
Well, the title does the trick... What is "voidspace" I can't find anything on npm or elsewhere on the web!

**Comment by lite20** [comment]
Ah. Sorry I should probably throw this in the wiki. Voidspace is a module I started developing primarily for Yunitto but I believe it will be useful for others too.

Voidspace lets programs in multiple nodejs instances to interchange variables and call RPC's (remote procedure calls. Aka running a function in a different program).

Think of voidspace as an advanced, nodejs edition of DBUS. Any program can open a namespace and start dumping variables and functions to be accessed and altered by other programs on the same system, or other systems if configured to do so.

**Comment by lite20** [comment]
@Coretool https://bitbucket.org/Lite20/voidspace here is the repository for Voidspace. I'll be pushing to it in about an hour.

**Comment by Coretool** [comment]
Good Job !

**Comment by Coretool** [comment]
So what are you planing on doing next; Is there something were I can help you ?

**Comment by lite20** [comment]
> So what are you planing on doing next; Is there something were I can help you ?

Well unfortunately, my daily amount of time for coding has been drastically shrunk. (parents)
So I'm going to make a todo list on the wiki and allow pull requests implementing the missing functionality. As a community we can piece it all together faster than I probably could have done it.

**Comment by lite20** [comment]
> Is there something were I can help you ?

It'd be great if you could lend a hand with Voidspace? :smile:

**Comment by Coretool** [comment]
I'm there to help ^^

**Comment by lite20** [comment]
Voidspace is officially a module on NPM! :smile:

> https://bitbucket.org/Lite20/voidspace

Here is the repository! A todo list is on the wiki

**Comment by lite20** [comment]
Voidspace is officially a module on NPM! :smile:

I put a todo list on the voidspace repo wiki. Once we finish voidspace we can finish Yunitto! ^_^

**Comment by Coretool** [comment]
Nice !

**Comment by Coretool** [comment]
What do you mean by secured pools ? Just an encryption ?

**Comment by lite20** [comment]
> What do you mean by secured pools ? Just an encryption ?

By secured pools I mean requesting authentication (a password) before allowing clients to be added to a pool. For that to work, we would need to store a map of keys for pools. We'd add to it when a secured pool is created, and verify that the passed key is correct when a client tries to connect.

wss should provide encryption, but if you have another idea for encryption, make a second fork and have at it.

**Comment by Coretool** [comment]
What about something like JSON-Webtokens ? We're using them for a client's webapp and they are very easy to implement (and secure of course) ! BTW: There are many RPC modules on npm , what about using one of those ?

**Comment by lite20** [comment]
> There are many RPC modules on npm , what about using one of those ?

The way Voidspace works, it would be easy to implement an RPC system, but maybe we could use another module. I'll take a look and see what's out there.

**Comment by Coretool** [comment]
All right, I see what I can come up with !

**Comment by lite20** [comment]
> All right, I see what I can come up with !

Awesome! Have you managed to get started on this, or should I paste it as a feature for the next release and simply release the new version of Voidspace?

**Comment by Coretool** [comment]
I got a concept... add it to the feature list for your next release! I haven't finished it yet and I think I have to make some bigger changes first... I will make a fork soon...

**Comment by lite20** [comment]
Added! Looking forward to seeing what you whip together!

**Comment by Coretool** [comment]
Hey! I managed to find a way to implement JWTs into voidspace! The messages that the server gets will be webtokens which will be read and the server will either rejecte them if the token isn't valid  (wrong encryption or the user who is trying connect isn't "registered" on the server) or pass it and exetuce the command in the tokens payload. 

How does this sound ? It would only require some changes to the `ws.on` part !

**Comment by lite20** [comment]
Sounds pretty neat!

**Comment by Coretool** [comment]
Well... It's pretty basic ☺

**Comment by lite20** [comment]
@Coretool Haha well, whenever you're ready, go for the pull!

**Comment by Coretool** [comment]
Sure, I got holiday ! I probably pull in the next days :)

**Comment by Coretool** [comment]
Pull request sent =)

**Comment by lite20** [comment]
And reply was sent! Looks very interesting! I've had to do some research on
JWT's to see how we would go about implemting it. My understanding is still
a bit sketchy though.
