### ISSUE TITLE
Text buffer in window

### ISSUE THREAD

**Issue by Compynerd255** [lite20/Yunitto#2]
As I mentioned in my [post](https://github.com/NodeOS/NodeOS/issues/201#issuecomment-169541589) in one of the NodeOS thread, a feature that I could see as being very useful for this or another NodeJS graphics project would be a portion of the screen that displays as pure text, following the same rules as a standard command line / xterm. The [Apple II](https://en.wikipedia.org/wiki/Apple_II_series) series of computers had a similar feature that displayed graphics on most of the screen but kept a window of 4 lines of text at the bottom. This was used to allow the BASIC user to continue typing to display graphics, but was also used for games and other applications that displayed a text HUD at the bottom of the screen and still allowed for command-line input. I think it would be useful if a similar feature was offered so that it could be used in NodeOS or in similar systems.

It would need the following features:
- When defining the framebuffer, an additional, optional parameter would define a partition in the graphics buffer for text. To simplify rendering, text would always be flush with one edge of the screen - there would be no picture-in-picture and both regions would always be rectangles. Graphics could possibly, however, be drawn behind it so that it appears when the text is removed.
- The size of the text combined with the dimensions of the box would define the size in characters of the text area. The text area would be a raw TTY in every sense - it reports a width and height, it accepts standard output, it inputs to standard input, it accepts all normal escape characters, it accepts coloring.
- Mouse support would be needed to the extent that clicking on the terminal will switch focus to it, but probably not much more than that.

**Comment by lite20** [comment]
> Mouse support would be needed to the extent that clicking on the terminal will switch focus to it, but probably not much more than that.

Awesome! I'm thinking of allowing applications using Yunitto to specify how they want users to interact with it. This of course can be the default functionality.

I also want to provide developers the ability to tamper as much as they please with it. I'm looking to potentiality just read and push to an actual tty so that standard Linux programs can access and interact with the tty as any normal program would, and Yunitto would simple offer "post-processing" features like the ones you mentioned.

**Comment by Compynerd255** [comment]
> I'm looking to potentiality just read and push to an actual tty so that standard Linux programs can access and interact with the tty as any normal program would, and Yunitto would simple offer "post-processing" features like the ones you mentioned.

That could be a good way of doing it - you allocate a TTY, and then you read from it to display the text.

And as far as my statement about mouse interaction: you wouldn't even need to include that in an alpha or even a beta release of Yunitto - just keyboard interaction by itself, including raw mode TTY interaction, would be just fine.

**Comment by lite20** [comment]
Yunitto just hit it's first beta a few seconds ago (woohoo!).

After discussing with @piranna Yunitto being a rendering layer, and only a rendering layer probably shouldn't be the project holding the console system.

So I've decided to write a module to do it so any program can use it. I'll use oven.js, an API I just wrote experimentally, to help push the API along. I feel it may do better for this. I'll create a repo for it on Github and tag you. If you'd like to contribute I'd be more than glad!

**Comment by Compynerd255** [comment]
> I'll create a repo for it on Github and tag you. If you'd like to contribute I'd be more than glad!

I'm not sure how much time I'll have with school and work and all, but it does seem like cool stuff! You can go ahead and tag me if you'd like.
